=== tgmz/sonar-xinfo-plugin/src/main/dtd/plicomp.dtd
<?xml encoding="UTF-8"?>
<!ELEMENT PACKAGE ((PROCEDURE)*,(MESSAGE)*,FILEREFERENCETABLE)>
<!ELEMENT PROCEDURE (BLOCKFILE,BLOCKLINE,(PROCEDURE)*,(BEGINBLOCK)*)>
<!ELEMENT BEGINBLOCK (BLOCKFILE,BLOCKLINE,(PROCEDURE)*,(BEGINBLOCK)*)>
<!ELEMENT MESSAGE (MSGNUMBER,MSGLINE?,MSGFILE?,MSGTEXT)>
<!ELEMENT FILE (FILENUMBER,INCLUDEDFROMFILE?,INCLUDEDONLINE?,FILENAME)>
<!ELEMENT FILEREFERENCETABLE (FILECOUNT,FILE+)>
<!ELEMENT BLOCKFILE (#PCDATA)>
<!ELEMENT BLOCKLINE (#PCDATA)>
<!ELEMENT MSGNUMBER (#PCDATA)>
<!ELEMENT MSGLINE (#PCDATA)>
<!ELEMENT MSGFILE (#PCDATA)>
<!ELEMENT MSGTEXT (#PCDATA)>
<!ELEMENT FILECOUNT (#PCDATA)>
<!ELEMENT FILENUMBER (#PCDATA)>
<!ELEMENT FILENAME (#PCDATA)>
<!ELEMENT INCLUDEDFROMFILE (#PCDATA)>
<!ELEMENT INCLUDEDONLINE (#PCDATA)>

=== tgmz/sonar-xinfo-plugin/testresources/xml/plitest5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plicomp SYSTEM "plicomp.dtd">
<PACKAGE>
<FILEREFERENCETABLE>
<FILECOUNT>2</FILECOUNT>
<FILE>
<FILENUMBER>0</FILENUMBER>
<FILENAME>PLITEST5</FILENAME>
</FILE>
<FILE>
<FILENUMBER>1</FILENUMBER>
<FILENAME>FOO</FILENAME>
<INCLUDEDFROMFILE>1</INCLUDEDFROMFILE>
<INCLUDEDONLINE>1</INCLUDEDONLINE>
</FILE>
</FILEREFERENCETABLE>
<PROCEDURE>
HALLO
<BLOCKFILE>
1
</BLOCKFILE>
<BLOCKLINE>
1
</BLOCKLINE>
</PROCEDURE>
<MESSAGE>
<MSGNUMBER>IBM1316I E</MSGNUMBER>
<MSGLINE>1</MSGLINE>
<MSGFILE>1</MSGFILE>
<MSGTEXT>BAR</MSGTEXT>
</MESSAGE>
<MESSAGE>
<MSGNUMBER>IBM00000 E</MSGNUMBER>
<MSGLINE>1</MSGLINE>
<MSGFILE>1</MSGFILE>
<MSGTEXT>FOO</MSGTEXT>
</MESSAGE>
</PACKAGE>

=== tgmz/sonar-xinfo-plugin/examples/xml/aplitest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plicomp SYSTEM "plicomp.dtd">
<PACKAGE>
<FILEREFERENCETABLE>
<FILECOUNT>
1
</FILECOUNT>
<FILE>
<FILENUMBER>0</FILENUMBER>
<FILENAME>SYS1.RULES.PLI(APLITEST)</FILENAME>
</FILE>
</FILEREFERENCETABLE>
<PROCEDURE>
HALLO
<BLOCKFILE>
1
</BLOCKFILE>
<BLOCKLINE>
1
</BLOCKLINE>
</PROCEDURE>
<MESSAGE>
<MSGNUMBER>IBM1316I E</MSGNUMBER>
<MSGLINE>3</MSGLINE>
<MSGFILE>0</MSGFILE>
<MSGTEXT>END label is not a label on any open group.</MSGTEXT>
</MESSAGE>
</PACKAGE>

=== tgmz/sonar-xinfo-plugin/sonar-xinfo-plugin/testresources/xml/aplitest10.xml
<?xml version='1.0' encoding='IBM-01140'?>
<!DOCTYPE plicomp SYSTEM 'plicomp.dtd'>
<PACKAGE>
<FILEREFERENCETABLE>
<FILECOUNT>1</FILECOUNT>
<FILE>
<FILENUMBER>0</FILENUMBER>
<FILENAME>Z39486.ZDEV.PLI(HELLOW)</FILENAME>
</FILE>
</FILEREFERENCETABLE>
<PROCEDURE>HELLOW
<BLOCKFILE>1</BLOCKFILE>
<BLOCKLINE>1</BLOCKLINE>
</PROCEDURE>
<MESSAGE>
<MSGNUMBER>IBM3317I W</MSGNUMBER>
<MSGLINE>7</MSGLINE>
<MSGFILE>0</MSGFILE>
<MSGTEXT>DSNH030I DSNHANAL LINE 7 COL 1  STATEMENT CONTAINS WRONG NUMBER OF &quot;INTO&quot; VARIABLES</MSGTEXT>
</MESSAGE>
<MESSAGE>
<MSGNUMBER>IBM3000I I</MSGNUMBER>
<MSGTEXT>DSNH4790I DSNHPSRV  DSNHDECP HAS CCSID 500 IN EFFECT</MSGTEXT>
</MESSAGE>
<MESSAGE>
<MSGNUMBER>IBM1043I I</MSGNUMBER>
<MSGLINE>12</MSGLINE>
<MSGFILE>0</MSGFILE>
<MSGTEXT>SYSPRINT is contextually declared as FILE.</MSGTEXT>
</MESSAGE>
</PACKAGE>

=== tgmz/sonar-xinfo-plugin/sonar-xinfo-plugin/testresources/xinfo/plitst8.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plicomp SYSTEM "plicomp.dtd">
<PACKAGE>
<FILEREFERENCETABLE>
<FILECOUNT>1</FILECOUNT>
<FILE>
<FILENUMBER>0</FILENUMBER>
<FILENAME>PLITEST8</FILENAME>
</FILE>
</FILEREFERENCETABLE>
<PROCEDURE>
HALLO
<BLOCKFILE>
1
</BLOCKFILE>
<BLOCKLINE>
1
</BLOCKLINE>
</PROCEDURE>
<MESSAGE>
<MSGNUMBER>IBM1213I W</MSGNUMBER>
<MSGLINE>1000</MSGLINE>
<MSGFILE>0</MSGFILE>
<MSGTEXT>The procedure SEQERR is not referenced.</MSGTEXT>
</MESSAGE>
<MESSAGE>
<MSGNUMBER>IBM2418I E</MSGNUMBER>
<MSGLINE>1</MSGLINE>
<MSGFILE>0</MSGFILE>
<MSGTEXT>Variable PLERROR is unreferenced.</MSGTEXT>
</MESSAGE>
<MESSAGE>
<MSGNUMBER>IBM1195I W</MSGNUMBER>
<MSGLINE>1</MSGLINE>
<MSGFILE>0</MSGFILE>
<MSGTEXT>Argument to MAIN procedure is not CHARACTER VARYING.</MSGTEXT>
</MESSAGE>
</PACKAGE>
